name: uniapp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

#firebase
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  provider: ^6.0.3
  flutter_launcher_icons: ^0.10.0
  loading_animation_widget: ^1.2.0+2
  blurry_modal_progress_hud: ^1.0.3
  flutter_spinkit: ^5.1.0
  progress_indicators: ^1.0.0
  flutter_neumorphic: ^3.2.0
  animations: ^2.0.7
  table_calendar: ^3.0.7
  custom_switch: ^0.0.1
  flutter_switch: ^0.3.2
  firebase_database: ^10.0.2
  cloud_firestore_odm: ^1.0.0-dev.37
  firebase_storage: ^11.0.4
  local_auth: ^2.1.2
  advance_pdf_viewer: ^2.0.1
  flutter_animation_progress_bar: ^2.3.1
  flutter_pdfview: ^1.2.5
  talkjs_flutter: ^0.2.1
  url_launcher: ^6.1.6
  firebase_messaging: ^14.0.4
  file_picker: ^5.2.2
  path_provider: ^2.0.11

flutter_icons:
 android: true
 ios: true
 image_path: "assets/TUM.logo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.3
flutter:
 
  uses-material-design: true

assets:
  - design1.png
  - design2.png
  - loginpagelogo.jpeg
  - topleft.png
