name: uniapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

#firebase
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  provider: ^6.0.3
  flutter_launcher_icons: ^0.9.3

flutter_icons:
 android: true
 ios: true
 image_path: "assets/TUM.logo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:


  uses-material-design: true

assets:
  - design1.png
  - design2.png
  - loginpagelogo.jpeg
