name: uniapp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

#firebase
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  provider: ^6.0.3
  flutter_launcher_icons: ^0.10.0
  loading_animation_widget: ^1.2.0+2
  blurry_modal_progress_hud: ^1.0.3
  flutter_spinkit: ^5.1.0
  progress_indicators: ^1.0.0
  flutter_neumorphic: ^3.2.0
  animations: ^2.0.7

flutter_icons:
 android: true
 ios: true
 image_path: "assets/TUM.logo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:


  uses-material-design: true

assets:
  - design1.png
  - design2.png
  - loginpagelogo.jpeg
  - topleft.png
